In [1]:
#The point of this script is to verify the correctness of a data file

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from mapping import Mapping

%load_ext version_information
%version_information numpy, pandas, matplotlib
%version_information
fig_prefix = "../figures/2018-07-22-jw-weaselball-starting_location_"
data_prefix = "../data/2018-07-22-jw-weaselball-starting_location_"

In [2]:
FLOAT_ERROR_TOLERANCE = 0.00000000001 #See IEEE 754 for why a floating point is never perfect
df_strings = ['../data/08-10-2018_09-24-59.csv']
frames = []
for csv in df_strings:
    temp = pd.read_csv(csv,index_col=False )
    frames.append(temp)
df = pd.concat(frames,ignore_index=True)
print(df.shape)
df = df.drop(columns=['Time'])
df = df.apply(pd.to_numeric)
df.head(10)

(21991, 8)

   ID         X       Y       Yaw  ResetID  checkCorrectness  NumberOfWalls
0   0  0.000000  0.0000  0.000000      1.0               0.0            0.0
1   0 -0.466000 -0.2796  0.083107      2.0               1.0            0.0
2   0 -0.465999 -0.2796  0.083107      2.0               1.0            0.0
3   0 -0.465999 -0.2796  0.083107      2.0               1.0            0.0
4   0 -0.465999 -0.2796  0.083107      2.0               1.0            0.0
5   0 -0.465998 -0.2796  0.083107      2.0               1.0            0.0
6   0 -0.465998 -0.2796  0.083107      2.0               1.0            0.0
7   0 -0.465998 -0.2796  0.083107      2.0               1.0            0.0
8   0 -0.465998 -0.2796  0.083107      2.0               1.0            0.0
9   0 -0.465998 -0.2796  0.083107      2.0               1.0            0.0

In [3]:
df.tail(10)

,ID,X,Y,Yaw,ResetID,checkCorrectness,NumberOfWalls
21981,0,0.056306,0.495093,-0.493175,3.0,1.0,0.0
21982,0,0.055826,0.495073,-0.493201,3.0,1.0,0.0
21983,0,0.055344,0.495051,-0.493227,3.0,1.0,0.0
21984,0,0.054863,0.495029,-0.493253,3.0,1.0,0.0
21985,0,0.054387,0.495012,-0.493274,3.0,1.0,0.0
21986,0,0.053900,0.494982,-0.493291,3.0,1.0,0.0
21987,0,0.053411,0.494948,-0.493307,3.0,1.0,0.0
21988,0,0.052923,0.494915,-0.493324,3.0,1.0,0.0
21989,0,0.052437,0.494884,-0.493344,3.0,1.0,0.0
21990,0,0.051951,0.494853,-0.493365,NaN,NaN,NaN

In [4]:
#Verify that the balls hit the wall at least once
walls_column = df['NumberOfWalls']
walls = {}
for i in walls_column:
    if i in walls:
        walls[i] += 1
    else:
        walls[i] = 1
walls

{0.0: 21314, 1.0: 676, nan: 1}